### ISSUE TITLE
Document that init method takes in a rot-13 encoded key.

### ISSUE THREAD

**Issue by chenposun** [eggheadgames/android-in-app-payments#14]
I've just started using this library for my app, and couldn't for the life of me figure out why I wasn't getting any responses from the server.

After debugging through the code, it turns out you guys are expecting a rot-13 encoded key in the init method. It might be a good idea to document that somewhere.

Nice work on the lib btw!

**Comment by mikemee** [comment]
@chenposun Doh!  You are so right!  We had moved this code from an internal source, where we had decided that passing around the key in plaintext was not a great idea (and I vaguely recall warnings in the Google docs about this). Rot-13 is hardly rocket science either, but it was a speed bump.

I'll add this to the docs right away.
