### ISSUE TITLE
How can I get details about my subscription ?

### ISSUE THREAD

**Issue by harshilkakadiyaplutus** [eggheadgames/android-in-app-payments#35]
How can I get my subscription details so that I can show that to the user.

**Comment by mikemee** [comment]
AFAIK Google and Amazon do not provide this. The best you can do is link to the URLs that they provide (typically in the respective app stores). 

At least this was the case when this library was created. I have not looked recently to see if Google or Amazon have improved this as subscriptions have become more popular.
