### ISSUE TITLE
Detect "already owned" message and unlock

### ISSUE THREAD

**Issue by mikemee** [eggheadgames/android-in-app-payments#8]
A Google Play customer reports that if she purchases on one device and then tries to refresh her 2nd device (using the same Play account), that the new purchase doesn't register for 1-2 days.

However, if she tries to purchase the same volume on the 2nd device, it says: "You already own this".  However, our library doesn't handle this and unlock the volume.

Is there something we can do about this, or are we at the mercy of Google?

**Comment by yurii-diachenko** [comment]
@mikemee it seems to me that it's Google's issue.
The reason why I think so is that:
1. I didn't find "You already own this" or similar neither in library nor in application
2. It refreshes only after 1-2 days but it does refrefreshes. In case  it's something wrong on our side it wouldn't be refreshed on the second device at all

**Comment by mikemee** [comment]
@yurii-diachenko I see this code in the docs `BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED` on this page: https://developer.android.com/google/play/billing/billing_reference.html.  Would we handle this correctly if it is returned?

Specifically, when I look in https://github.com/eggheadgames/android-in-app-payments/blob/master/library/src/main/java/com/android/vending/billing/IabHelper.java, I see it is declared, but it never seems to be used.  

Perhaps the Google example that we based this on never checked for this scenario ... and we should?

**Comment by mikemee** [comment]
Possibly helpful / related:

https://stackoverflow.com/questions/23696088/in-app-billing-verify-already-owned-result

https://stackoverflow.com/questions/31533335/inappbilling-v3-iabresult-response-code-billing-response-result-item-already-own

I think the sample code is trying to be careful about un-managed items (aka consumables) which can only be used on one device. But as our scenario has managed items, we want to allow customers to use the purchase immediately instead of having to wait 1-2 days.

**Comment by yurii-diachenko** [comment]
Makes sense, I'll take a closer look

**Comment by mikemee** [comment]
@yurii-diachenko Here's a screenshot that a customer sent us in case it helps:

![2016-12-09_17-16-50](https://cloud.githubusercontent.com/assets/550990/21069902/5e1adbe0-be33-11e6-8c36-806125685b7d.png)
